### ISSUE TITLE
In the template definitions tab indicate whether it is single option or multiple option question

### ISSUE THREAD

**Issue by joycarpediem** [akvo/wai-ethiopia#62]

**Comment by dedenbangkit** [comment]
We have this feature, but we don't have it in the intial question definition, we need to asked Franky or Francis

**Comment by dedenbangkit** [comment]
Type of question: https://github.com/akvo/wai-ethiopia/blob/053f2e6c8c685225df15865573d1f140f27267b6/backend/models/question.py#L13-L24

------

More detail:

- Excel Generator: https://github.com/akvo/wai-ethiopia/blob/main/backend/util/excel.py

- Validation Tests: https://github.com/akvo/wai-ethiopia/blob/main/backend/tests/test_08_excel_validation.py

Or you could also try to create new question via Swagger with multiple option type of question, then download the template from admin page
