### ISSUE TITLE
Add meta data to data export

### ISSUE THREAD

**Issue by joycarpediem** [akvo/wai-ethiopia#83]
The filter with which the data was created and the date the file was generated

**Comment by joycarpediem** [comment]
Sheet name : Context
Date of file generation
Filter

**Comment by dedenbangkit** [comment]
Duplicate of [#75](https://github.com/akvo/wai-ethiopia/issues/75#issuecomment-964826180)

**Comment by dedenbangkit** [comment]
IN THE FILE
